package com.cambiahealth.ahs.entity;

/**
 * Created by CrazyBS on 2/24/2016.
 */
public enum NdwMember implements FixedWidth {
    NDW_PLAN_ID(3),
    HOME_PLAN_PRODUCT_ID(15),
    NDW_PRODUCT_CATEGORY_CODE(3),
    MEMBER_ID(22),
    CONSISTENT_MEMBER_ID(22),
    MEMBER_DATE_OF_BIRTH(8),
    MEMBER_GENDER(1),
    MEMBER_CONFIDENTIALITY_CODE(3),
    COVERAGE_BEGIN_DATE(8),
    COVERAGE_END_DATE(8),
    MEMBER_RELATIONSHIP(2),
    ITS_SUBSCRIBER_ID(17),
    GROUP_OR_INDIVIDUAL_CODE(10),
    ALPHA_PREFIX(3),
    MEMBER_PREFIX(20),
    MEMBER_LAST_NAME(150),
    MEMBER_FIRST_NAME(70),
    MEMBER_MIDDLE_INITIAL(2),
    MEMBER_SUFFIX(20),
    MEMBER_PRIMARY_STREET_ADDRESS_1(70),
    MEMBER_PRIMARY_STREET_ADDRESS_2(70),
    MEMBER_PRIMARY_CITY(35),
    MEMBER_PRIMARY_STATE(2),
    MEMBER_PRIMARY_ZIP_CODE(5),
    MEMBER_PRIMARY_ZIP_CODE_4(4),
    MEMBER_PRIMARY_PHONE_NUMBER(10),
    MEMBER_PRIMARY_EMAIL_ADDRESS(70),
    MEMBER_SECONDARY_STREET_ADDRESS_1(70),
    MEMBER_SECONDARY_STREET_ADDRESS_2(70),
    MEMBER_SECONDARY_CITY(35),
    MEMBER_SECONDARY_STATE(2),
    MEMBER_SECONDARY_ZIP_CODE(5),
    MEMBER_SECONDARY_ZIP_CODE_4(4),
    HOST_PLAN_OVERRIDE(3),
    MEMBER_PARTICIPATION_CODE(1),
    MEMBER_MEDICAL_COB_CODE(1),
    VOID_INDICATOR(1),
    MMI_INDICATOR(22),
    HOST_PLAN_CODE(3),
    HOME_PLAN_CORPORATE_PLAN_CODE(3),
    PHARMACY_CARVE_OUT_INDICATOR(1);

    private int width;

    NdwMember(int fixedWidth) {
        width = fixedWidth;
    }

    public int getFixedWidth() {
        return width;
    }
}
